language: node_js
node_js:
- '6'
sudo: false
script: npm run $COMMAND
before_script:
- npm run lint
env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
  - COMMAND=test-phantom
  - COMMAND=report-coverage
  global:
  - secure: MdlxTrVgt8PDWRsSKCwmX8H9ybARy4scF2jIZu3BiGALumIcBEztOZry8OIbacrhIGRsM8hCumQjszt5oUqB0af2lZWtDjPa56tTYZNlzeH+k0SOgSfLHRNWG5aD5o5UPczeK79FFaptUagpl8LBsU7oEeQrIxaieLyNbLXhmRqTM0CTQOd5u9+GOvhn+3wQxEag7pT8JqxPvS89GAnuT+kA4aBgtJgQbaA4gyWDzqI8F3BcMaNyPsk0OQlS7xMDtpRygttM+0RI3b7z8eYXARLbgjDs2DSUxtFmmOv16m2kPlC2E7oSlB+6O8SSrYldrHdWoNvwduyDba3Ir8/42dVhFEi15MiaKIuAOte00UYZ40p7RHiS38F9QIEccLenfg0VAy8yC1qMaIzr/75sdnkO5CnfnLYWGr37sj1slUrUZi35PDM0i8Q4RHQc+nNATkgnghReLhImGfxpJy735s5c+8ItJntlAOiV7p1ufoGO+JfAwvSGIg3pYvXt7x2FQn0h/lsD/OPOUz38PnqNW88Ov1wHJkhjAsrzhS5langl4NsqvwiM/AtS4DsEqQ27s7Co1rczD0uH/LI/kaoHoE2ITfr1C3qtWK69ofhPrTCU9cJHE30EvARHU/FJyZeIvuUqIs6IOp+56DbUPFopOzntWSr6eEdoVQC09bY9ObQ=
  - secure: nBu4Jci01Rf9bZxnyw+WoBl8hSnNyRyWSHSgX1ODs+SAU+ItRi/xMUqNkF2f87e/KxwvHcKAx4IHz3zt2eRPKoYN5+yzX0wTamLUDwJ4TZvffuF2s3XpSrbpBkZcQUK1vIVQpxKwgzF3VSKYtCpbzei/R3gxHvlwGW2gqoTt8oofvwiPF+kLMJGW+XYdcV1/1LhbYPgTCL+tMPFmz3/UeGAa3QJNyD4AoHmUK45o/A4Sl5QahjNFlpFmmiaUNjOGPDs6ZKsUgw+TOt1yiXntCi8jm/9uCYy831x9x27tjXNWufVj2vrcdnuIenM0fgmFGt2jxfyLncUz2/uN+Vutd4VIICj69m7wj4X720ZNRG6Fs0U8LMyypWv+SvXYMRlQQQvrQupjSxH2IEE0M4C1WyRmm0AdbZ4i92BJ9kbSs2TBuYz7Of3iwXrFjL/YnK8JG4WLKAzLlJ4DhhtSjPLIw7YMGEZlrsaJZ49dU2p58E7U1VjYHeREIfFagZWzgdhQUYK/RB2oV3xta/BSYwspDtDk6uiJ+lf1ZyFzY59EdqpQQteLfAdNG1fHHbXt2P3SJJapkYYut3pkVUQyb3Zw11rp6LZSfAye2ft8q8WjEtgvzT2ZJZgdUq1hwbS2M9yULepkHXKQgrIuFh+GwM0wC5KM77og2r4GKwztsIG0cdo=
  - secure: p9Ewvw/niBZS5E/h2lHiB+P9uXnMzK0jVV/0S0GnwY30cSsn5mJ0Zly2Hlc0uwQShHougUiFqioiBf+EPl5lYyvtZI/ndh8KcyugHJn7yXMxprN1DI1f1oxGFEIZx4EqkUxKSZR28L+nMZvr9EU8rxB+H9rH9wqWwH5pk65SajskkBCrZULzChpJdMd/hjz9fdHigP/6x6VN9jPUqeUODjuZEgwq2CNSDz/VPCazIFdAt/OMJsrlE9zzBguL9NqyA48tO7n5oN/Ra8idQVe+TfyxTSuJd+Gbv2i72mcQqrkkhMxunll0/JlnP5JBiJIMSWCH/4SXcjs2mEe5W3j18EMDX7yL3Had3BYlOaWW7eKEtCBoYXxkqX3lzaKgHOrolDi7Y2OF6jCBli0JB7YjUnmjAxMftHH8s/iVS7WjHsacSju0hTETNH4fyDSxzdzcLD4iiyTLmyBV8Czl2icc9TXwEMe9XEHiklH7XmN0GgJB92Npb6CC77Kf7tgjxnazU/prdnXuPR9yRmJ8AdzX5g1KmuWzxhLw+8orZbMHjUudQdVs/HBqkdsslRcvsQkfb6xhtY6HVMGg8MITv+SMXtCpsaHknrJSKG9Rh/AhcT5wMQsVZ5FoL7Zbnyw7uVOHItWEi/qORE3UJo85UVp4tj0CyEbRousX3dpYoPo9CYk=
branches:
  only:
  - master
